server:
  port: 8600

#设置应用名称
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: coumster
          uri: http://localhost:8602
          predicates:
            - Path=/Hello/**

#        - id: login
#          uri: http://localhost:8603
#          predicates:
#            - Path=/**




